---
apiVersion: v1
kind: Service
metadata:
  name: assistant
  namespace: argocd
  labels:
    app: assistant
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: assistant
