version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      timezone: "Europe/Berlin"

  - package-ecosystem: npm
    directory: "/apps/backend"
    schedule:
      interval: daily
      timezone: "Europe/Berlin"

  - package-ecosystem: npm
    directory: "/apps/extension"
    schedule:
      interval: daily
      timezone: "Europe/Berlin"

  - package-ecosystem: npm
    directory: "/packages/argocd"
    schedule:
      interval: daily
      timezone: "Europe/Berlin"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      timezone: "Europe/Berlin"
